Add filter to JSON data sources
smutel/terraform-provider-netbox pull request #175
Opened 2023-01-30 11:10 UTC by jgrexa

Add possibility to filter JSON datasources.
For example:
```
data "netbox_json_ipam_prefixes_list" "test" {
  limit = 0
  filter {
    name = "foo"
    value = "bar"
  }
  filter {
    name = "foo_n"
    value = "barbar" 
}
```

2023-01-30 13:04 UTC, smutel requested changes
Thank you for your PR.

2023-01-31 13:22 UTC, smutel commented
Could you please fixup you commit with the message "feat: Add filter to JSON data sources".  
Could you please also create an issue linked to this PR.

Thanks.

2023-01-31 13:37 UTC, jgrexa commented
Title updated & issue created.

2023-01-31 16:46 UTC, smutel approved these changes

2023-01-31 16:46 UTC, merged