Add ability to return json objects of all endpoints
smutel/terraform-provider-netbox pull request #19
Opened 2020-11-21 23:03 UTC by sc0ttes

Should be all good to go this time!

2020-11-22 08:59 UTC, smutel commented
Thank you for this new PR.
Only one thing, could you please prefix your commit comment by `feat: `.

2020-11-28 09:13 UTC, smutel commented
Hello, now your commit is correct but you have a merge item from master, I don't know why.

Could you please sync the master in your repo with the master in my repo (Add origin / git fetch origin / git merge origin/master) ?

Then go to your branch and type git rebase origin/master.

Thanks again.

2020-12-03 13:21 UTC, sc0ttes commented
Hey Samuel,

Should be all fixed now. My master had been out of sync with yours so last time I got mine back in sync, I merged it into json_endpoints without rebasing afterwards.

2020-12-03 13:31 UTC, smutel commented
Sorry you have some minor lint issues to resolve: https://github.com/smutel/terraform-provider-netbox/pull/19/checks#step:4:26

2020-12-04 07:35 UTC, smutel requested changes

2020-12-04 07:35 UTC, smutel commented on utils/netbox_generate_json_datasources.sh
> +func dataNetboxJson${SECTION}${ITEM}List() *schema.Resource {
```suggestion
func dataNetboxJSON${SECTION}${ITEM}List() *schema.Resource {
```

2020-12-04 07:35 UTC, smutel commented on utils/netbox_generate_json_datasources.sh
> +                Read: dataNetboxJson${SECTION}${ITEM}ListRead,
```suggestion
                Read: dataNetboxJSON${SECTION}${ITEM}ListRead,
```

2020-12-04 07:35 UTC, smutel commented on utils/netbox_generate_json_datasources.sh
> +func dataNetboxJson${SECTION}${ITEM}ListRead(d *schema.ResourceData, m interface{}) error {
```suggestion
func dataNetboxJSON${SECTION}${ITEM}ListRead(d *schema.ResourceData, m interface{}) error {
```

2020-12-04 07:35 UTC, smutel commented on utils/netbox_generate_json_datasources.sh
> +        d.SetId("NetboxJson${SECTION}${ITEM}List")
```suggestion
        d.SetId("NetboxJSON${SECTION}${ITEM}List")
```

2020-12-04 07:35 UTC, smutel commented on utils/netbox_generate_json_datasources.sh
> +"netbox_json_${ENDPOINT}_list": dataNetboxJson${SECTION}${ITEM}List(),
```suggestion
"netbox_json_${ENDPOINT}_list": dataNetboxJSON${SECTION}${ITEM}List(),
```

2020-12-11 15:54 UTC, smutel commented
@sc0ttes  ?

2021-01-01 19:58 UTC, smutel commented
Thank your contribution. I rewrote some part in #37.

2021-01-01 19:58 UTC, closed without merging

2021-01-24 03:14 UTC, sc0ttes commented
Sorry got really busy at work but thanks for merging!!